name: Code Formatter

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - '.github/workflows/code_formatter.yml'

jobs:
  push_format:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir uv
          uv pip install --no-cache-dir -U black isort autoflake -q --system

      - name: Run autoflake
        run: autoflake --in-place --recursive .

      - name: Run isort
        run: isort .

      - name: Run Black
        run: black . --line-length 140

      - name: Check for changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=has_changes::true"
          else
            echo "::set-output name=has_changes::false"
          fi

      - name: Commit changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Automatic code formatting"

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          delete-branch: true
          body: "Automatic code formatting"
          title: "Automatic code formatting"
          commit-message: "Automatic code formatting"
          branch: formatter/main
